[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
spirv = { path = "../spirv" }
vulkan = { path = "../vulkan" }
math = { path = "../math" }
winit = "0.30.12"
ash = "0.38.0"
ash-window = "0.13.0"
image = "0.25.9"

[build-dependencies]
spirv = { path = "../spirv" }
